#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing your project before committing'

npm run format
npm run lint
npm test

# If everything passes... Now we can commit
echo '✅ You win this time... I am committing this now.'
